### ISSUE TITLE
GPU process crashed issue.

### ISSUE THREAD

**Issue by umairzahid508** [electromaggot/MacChromiumStoryboard#2]
I have successfully clone your project and build it but after running the project the program crashed with the error message of "The GPU process has crashed 9 time(s)" and second one is "FATAL:gpu_data_manager_impl_private.cc(417)] GPU process isn't usable. Goodbye."

Thank you.
I am waiting for your response.

**Comment by electromaggot** [comment]
Sorry, I can no longer support this project and won't be able to offer any assistance.  The project it's based on is too old and also now unsupported.  Hopefully the code can still somehow be helpful to someone.  Closing issue as "won't/can't fix."
